name: bundler
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: NPM Installation
        run: |
          pwd
          npm install
      - name: Webpack
        run: npm run bundle
