name: bundler
on: push
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
     - name: NPM Installation
       run: |
        pwd
        npm install
     - name: Webpack
       run: npm run bundle
